services:

  redis:
    image: redis:7-alpine
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:






# version: "3.9"

# services:
#   redis:
#     image: redis:7-alpine
#     networks:
#       - app-network
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 5s
#       retries: 5
#     deploy:
#       resources:
#         limits:
#           cpus: "0.5"
#           memory: 256M

#   api:
#     build: ./api
#     ports:
#       - "8000:8000"
#     environment:
#       - REDIS_HOST=redis
#     depends_on:
#       redis:
#         condition: service_healthy
#     networks:
#       - app-network
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
#       interval: 5s
#       retries: 5
#     deploy:
#       resources:
#         limits:
#           cpus: "0.5"
#           memory: 256M

#   worker:
#     build: ./worker
#     environment:
#       - REDIS_HOST=redis
#     depends_on:
#       redis:
#         condition: service_healthy
#     networks:
#       - app-network
#     deploy:
#       resources:
#         limits:
#           cpus: "0.5"
#           memory: 256M

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:3000"
#     environment:
#       - API_URL=http://api:8000
#     depends_on:
#       api:
#         condition: service_healthy
#     networks:
#       - app-network
#     deploy:
#       resources:
#         limits:
#           cpus: "0.5"
#           memory: 256M

# networks:
#   app-network: